import { ComputeEngine, AIModel, UserSettings } from '@/types';

export const DEFAULT_SETTINGS: UserSettings = {
  computeEngine: 'pollinations',
  defaultModel: 'flux',
  defaultSampler: 'Euler a',
  defaultAspectRatio: '1:1',
  defaultBatchCount: 1,
  defaultSteps: 25,
  defaultGuidance: 8.0,
  defaultStyleStrength: 0.65,
  defaultLoraWeight: 0.5,
  defaultNegativePrompt: 'blurry, low quality, distorted, bad hands, bad face, deformed',
  darkMode: false,
  historyLimit: 50,
  enableD1Sync: false,
  enableNsfw: true,
  autoEnhancePrompt: true,
};

export const SAMPLING_METHODS = [
  'Euler a',
  'DPM++ 2M Karras',
  'DPM++ SDE Karras',
  'DDIM',
  'LCM',
  'UniPC',
];

export const SCHEDULER_TYPES = [
  'Karras',
  'Exponential',
  'Normal',
  'SGM Uniform',
  'Simple',
];

export const ASPECT_RATIOS = [
  { label: '1:1 正方形', value: '1:1', icon: '⏹️', w: 1024, h: 1024 },
  { label: '16:9 横屏', value: '16:9', icon: '🖥️', w: 1280, h: 720 },
  { label: '9:16 手机屏', value: '9:16', icon: '📱', w: 720, h: 1280 },
  { label: '4:3 经典屏', value: '4:3', icon: '🖼️', w: 1024, h: 768 },
  { label: '3:4 竖屏', value: '3:4', icon: '📄', w: 768, h: 1024 },
];

export const COMPUTE_ENGINES: ComputeEngine[] = [
  {
    id: 'pollinations',
    name: 'Pollinations 免费全能算力池 (推荐首选)',
    type: 'pollinations',
    description: '免 API Key，支持 FLUX, SDXL, Turbo，秒级高质量生成',
    isDefault: true,
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI (边缘计算)',
    type: 'cloudflare-ai',
    description: '全球边缘节点低延迟推理，支持 CF 免费额度与 Token 接入',
    isDefault: false,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow 硅基流动云算力',
    type: 'custom-api',
    endpoint: 'https://api.siliconflow.cn/v1/image/generations',
    description: '国内极速 FLUX.1 / SDXL 高清生成',
    isDefault: false,
  },
  {
    id: 'openai',
    name: 'OpenAI DALL-E 3 官方引擎',
    type: 'dall-e',
    description: '顶级语言理解能力，画质高逼真',
    isDefault: false,
  },
  {
    id: 'stability',
    name: 'Stability AI 官方节点',
    type: 'stable-diffusion',
    description: 'SDXL 1.0 官方画质模型',
    isDefault: false,
  },
];

// Exactly 30 preset models with translations and pricing badges
export const AI_MODELS: AIModel[] = [
  {
    id: 'flux',
    name: 'FLUX.1 极速旗舰版 (画质王者)',
    translatedName: 'FLUX.1 极速画质王者',
    description: 'Black Forest Labs 顶级画质大模型，出图逼真、细节震撼',
    provider: 'pollinations',
    category: 'flux',
    isPopular: true,
    isFavorite: true,
    isFree: true,
  },
  {
    id: 'flux-realism',
    name: 'FLUX Realism 写实摄影版',
    translatedName: 'FLUX 写实摄影大模型',
    description: '专注于摄影级肖像、自然光影与超清晰肌理细节',
    provider: 'pollinations',
    category: 'realistic',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'flux-anime',
    name: 'FLUX Anime 二次元大师版',
    translatedName: 'FLUX 动漫美学大模型',
    description: '极致细腻的二次元画风、水彩插画与唯美动漫构图',
    provider: 'pollinations',
    category: 'anime',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'flux-3d',
    name: 'FLUX 3D CG 电影渲染版',
    translatedName: 'FLUX 3D CG 画质大模型',
    description: '媲美皮克斯与虚幻引擎 3D 渲染质感',
    provider: 'pollinations',
    category: '3d',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'turbo',
    name: 'SDXL Turbo 闪电极速版',
    translatedName: 'SDXL Turbo 极速大模型',
    description: '秒级极速生成，适合快速创意探索',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:animagine-xl-3.1',
    name: 'Animagine XL 3.1 动漫大师版',
    translatedName: 'Animagine 二次元大师 3.1',
    description: '专业日系动漫插画模型，线条极佳',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:cyberrealistic-v4.1',
    name: 'CyberRealistic V4.1 赛博写实',
    translatedName: 'CyberRealistic 赛博现实主义',
    description: '真实肖像、光彩肌理与摄影级质感',
    provider: 'pollinations',
    category: 'realistic',
    isFree: true,
  },
  {
    id: 'civitai:dreamshaper-xl-v2',
    name: 'DreamShaper XL V2 梦幻塑造者',
    translatedName: 'DreamShaper 梦幻大模型 V2',
    description: '兼顾写实与奇幻艺术创作',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:ink-wash-painting-xl',
    name: 'Ink Wash Painting 水墨国风',
    translatedName: '水墨写意传统国风大模型',
    description: '诗情画意的水墨宣纸质感',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:ghibli-style-xl',
    name: 'Ghibli Style 吉卜力治愈风',
    translatedName: '吉卜力吉风治愈系大模型',
    description: '宫崎骏动画般阳光清新色彩',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:midjourney-v6-style',
    name: 'Midjourney V6 艺术美学预设',
    translatedName: 'MJ V6 艺术美学构图版',
    description: '震撼光影与艺术构图质感',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:anything-v5',
    name: 'Anything V5 经典二次元',
    translatedName: 'Anything V5 通用动漫版',
    description: '经典通用型动漫绘图大模型',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:counterfeit-v3.0',
    name: 'Counterfeit V3.0 日系手绘',
    translatedName: 'Counterfeit 手绘拟真动漫',
    description: '复古日系手绘与油画肌理效果',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:deliberate-v3',
    name: 'Deliberate V3 深思纪实版',
    translatedName: 'Deliberate 精细纪实 V3',
    description: '丰富细节与自然构图的纪实写真',
    provider: 'pollinations',
    category: 'realistic',
    isFree: true,
  },
  {
    id: 'civitai:realcartoon-xl-v6',
    name: 'RealCartoon XL V6 拟真欧美漫',
    translatedName: 'RealCartoon 3D 美漫写实',
    description: '迪士尼与皮克斯级别的 3D 质感',
    provider: 'pollinations',
    category: '3d',
    isFree: true,
  },
  {
    id: 'civitai:vray-3d-render-xl',
    name: 'V-Ray 3D Render XL 超清渲染器',
    translatedName: 'V-Ray 3D 渲染大模型',
    description: '媲美电影级 3D CG 渲染效果',
    provider: 'pollinations',
    category: '3d',
    isFree: true,
  },
  {
    id: 'civitai:cinematic-photography-v2',
    name: 'Cinematic Photography 电影剧照',
    translatedName: '电影胶片光影摄影版',
    description: '景深变焦与大师级构图氛围',
    provider: 'pollinations',
    category: 'realistic',
    isFree: true,
  },
  {
    id: 'civitai:cyberpunk-neon-city-xl',
    name: 'Cyberpunk Neon 赛博霓虹城市',
    translatedName: '赛博霓虹科幻大模型',
    description: '高对比霓虹与未来都市构图',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:watercolor-art-v3',
    name: 'Watercolor Art 灵动水彩画',
    translatedName: '灵动水彩纸张插画版',
    description: '晕染水彩与细腻纸张边缘',
    provider: 'pollinations',
    category: 'sd15',
    isFree: true,
  },
  {
    id: 'civitai:oil-painting-master-xl',
    name: 'Oil Painting Master 印象派油画',
    translatedName: '经典油画大师肌理版',
    description: '厚重笔触与古典油画光影',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:pixel-art-master-v2',
    name: 'Pixel Art Master 像素复古风',
    translatedName: '像素艺术复古游戏版',
    description: '像素点阵与复古电子游戏氛围',
    provider: 'pollinations',
    category: 'sd15',
    isFree: true,
  },
  {
    id: 'civitai:chibi-sticker-cute',
    name: 'Chibi Cute Sticker Q版萌系贴纸',
    translatedName: 'Q版萌系表情贴纸版',
    description: '可爱线条与纯色干净背景',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:isometric-3d-diorama',
    name: 'Isometric 3D Diorama 等距微缩',
    translatedName: '等距 3D 微缩景观模型',
    description: '精致立体等距切片模型',
    provider: 'pollinations',
    category: '3d',
    isFree: true,
  },
  {
    id: 'civitai:dark-fantasy-gothic',
    name: 'Dark Fantasy Gothic 哥特暗黑范',
    translatedName: '哥特奇幻暗黑画质版',
    description: '幽暗光影与古典哥特美学',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:low-poly-art-3d',
    name: 'Low Poly Art 3D 低多边形',
    translatedName: 'Low Poly 低多边形 3D',
    description: '现代几何切面与明亮色彩',
    provider: 'pollinations',
    category: '3d',
    isFree: true,
  },
  {
    id: '@cf/bytedance/stable-diffusion-xl-lightning',
    name: 'ByteDance Lightning (Cloudflare)',
    translatedName: '字节跳动 闪电大模型',
    description: 'Cloudflare 边缘极速 4-步推理模型',
    provider: 'cloudflare',
    category: 'sdxl',
    cfModelPath: '@cf/bytedance/stable-diffusion-xl-lightning',
    needsApiKey: true,
  },
  {
    id: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    name: 'Cloudflare SDXL Base 1.0',
    translatedName: 'Cloudflare SDXL 原生模型',
    description: 'Cloudflare 边缘原生高清晰度模型',
    provider: 'cloudflare',
    category: 'sdxl',
    cfModelPath: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    needsApiKey: true,
  },
  {
    id: 'black-forest-labs/FLUX.1-schnell',
    name: 'SiliconFlow FLUX.1 Schnell',
    translatedName: '硅基流动 FLUX 极速版',
    description: 'SiliconFlow 托管高效率模型',
    provider: 'custom',
    category: 'flux',
    needsApiKey: true,
  },
  {
    id: 'dall-e-3',
    name: 'OpenAI DALL·E 3 官方引擎',
    translatedName: 'DALL·E 3 官方画质模型',
    description: 'OpenAI 官方旗舰图像引擎',
    provider: 'openai',
    category: 'realistic',
    needsApiKey: true,
  },
  {
    id: 'stability-sdxl-1.0',
    name: 'Stability AI SDXL 1.0 官方版',
    translatedName: 'Stability SDXL 1.0 官方大模型',
    description: 'Stability 官方 1024 级引擎',
    provider: 'custom',
    category: 'sdxl',
    needsApiKey: true,
  },
];

export const PRESET_MODELS = AI_MODELS;
