import { AIModel, ComputeEngine } from '@/types';

export const COMPUTE_ENGINES: ComputeEngine[] = [
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion (默认算力引擎)',
    type: 'stable-diffusion',
    description: '标准 SD WebUI / AUTOMATIC1111 / ComfyUI / SDXL 接口引擎',
    isDefault: true,
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI',
    type: 'cloudflare-ai',
    description: 'Cloudflare 边缘极速神经网络推理与生成平台',
  },
  {
    id: 'pollinations',
    name: 'Pollinations 公共算力集群',
    type: 'pollinations',
    description: '全球分布式免费高性能 GPU 图形算力节点',
  },
  {
    id: 'custom-api',
    name: '自定义 OpenAI / ComfyUI 兼容 API',
    type: 'custom-api',
    description: '接入个人私有服务器、OpenRouter 或第三方绘图 API',
  },
];

export const DEFAULT_SETTINGS = {
  computeEngine: 'stable-diffusion',
  defaultModel: 'sdxl-base-1.0',
  defaultAspectRatio: '1:1',
  defaultSteps: 20,
  defaultGuidance: 7.5,
  darkMode: false,
  historyLimit: 50,
  enableD1Sync: true,
};

export const ASPECT_RATIOS = [
  { label: '1:1 正方形', value: '1:1', width: 1024, height: 1024 },
  { label: '16:9 宽屏', value: '16:9', width: 1280, height: 720 },
  { label: '9:16 竖屏/手机', value: '9:16', width: 720, height: 1280 },
  { label: '4:3 传统横屏', value: '4:3', width: 1024, height: 768 },
  { label: '3:4 传统竖屏', value: '3:4', width: 768, height: 1024 },
];

export const PRESET_MODELS: AIModel[] = [
  // Stable Diffusion Out-of-the-Box Models (Default Factory Setup)
  {
    id: 'sdxl-base-1.0',
    name: 'Stable Diffusion XL 1.0 (出厂默认)',
    translatedName: 'Stable Diffusion XL 1.0 (出厂默认)',
    description: 'Stability AI 旗舰 Stable Diffusion 核心出厂模型',
    provider: 'stable-diffusion',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: 'sd-v1-5',
    name: 'Stable Diffusion v1.5',
    translatedName: 'Stable Diffusion 1.5 经典版',
    description: '经典 SD 1.5 模型，兼容性极高，绘图稳定度出众',
    provider: 'stable-diffusion',
    category: 'sd15',
    isPopular: true,
  },
  {
    id: 'sdxl-turbo',
    name: 'SDXL Turbo Realtime',
    translatedName: 'SDXL Turbo 实时极速版',
    description: '单步或少量步数下极速出图的 SD 实时模型',
    provider: 'stable-diffusion',
    category: 'sdxl',
  },
  // Cloudflare Workers AI Models
  {
    id: '@cf/bytedance/stable-diffusion-xl-lightning',
    name: 'SDXL Lightning (ByteDance)',
    translatedName: 'SDXL 极速版 (字节跳动)',
    description: 'Cloudflare 官方超高速 SDXL 生成模型，质感优异',
    provider: 'cloudflare',
    cfModelPath: '@cf/bytedance/stable-diffusion-xl-lightning',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    name: 'SDXL Cloudflare Base 1.0',
    translatedName: 'SDXL Cloudflare 基础版 1.0',
    description: 'Cloudflare Workers AI 深度整合版 SDXL 基础设施',
    provider: 'cloudflare',
    cfModelPath: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    category: 'sdxl',
  },
  {
    id: '@cf/lykon/dreamshaper-8-lcm',
    name: 'DreamShaper 8 LCM',
    translatedName: '梦境塑造者 8 极速版',
    description: '二次元与全能艺术风格兼备，生成速度极快',
    provider: 'cloudflare',
    cfModelPath: '@cf/lykon/dreamshaper-8-lcm',
    category: 'anime',
    isPopular: true,
  },
  {
    id: '@cf/runwayml/stable-diffusion-v1-5',
    name: 'Cloudflare SD 1.5',
    translatedName: 'Cloudflare 托管 SD 1.5',
    description: 'Cloudflare 边缘算力跑 SD 1.5',
    provider: 'cloudflare',
    cfModelPath: '@cf/runwayml/stable-diffusion-v1-5',
    category: 'sd15',
  },
  // Public models & Pollinations models
  {
    id: 'flux',
    name: 'FLUX.1 Schnell',
    translatedName: 'FLUX.1 极速版',
    description: '最新一代开源绘图模型，文字排版与真实质感极佳',
    provider: 'pollinations',
    category: 'flux',
    isPopular: true,
  },
  {
    id: 'flux-realism',
    name: 'FLUX Realism Ultra',
    translatedName: 'FLUX 逼真超清版',
    description: '超强人像与摄影纪实质感',
    provider: 'pollinations',
    category: 'realistic',
    isPopular: true,
  },
  {
    id: 'flux-anime',
    name: 'FLUX Anime Dream',
    translatedName: 'FLUX 动漫幻想',
    description: '精美日系动漫与插画风格',
    provider: 'pollinations',
    category: 'anime',
    isPopular: true,
  },
  {
    id: 'flux-3d',
    name: 'FLUX 3D Render',
    translatedName: 'FLUX 3D 渲染器',
    description: '立体 3D 角色与三维场景建模效果',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon V2',
    translatedName: '赛博朋克 霓虹 V2',
    description: '强烈的科幻霓虹与未来城市风格',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'watercolor',
    name: 'Watercolor Romance',
    translatedName: '浪漫水彩画',
    description: '柔美优雅的手绘水彩意境',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'cinematic',
    name: 'Cinematic Movie Shot',
    translatedName: '电影级景深大片',
    description: '高对比度、电影光影与质感滤镜',
    provider: 'pollinations',
    category: 'realistic',
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art Retro 8-bit',
    translatedName: '复古 8Bit 像素风',
    description: '经典像素游戏美术与图表风格',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'ink-painting',
    name: 'Chinese Ink Wash Painting',
    translatedName: '中国写意水墨画',
    description: '传统国画水墨晕染与山水意境',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'architecture',
    name: 'Architectural Design Concept',
    translatedName: '现代建筑设计效果图',
    description: '专业室内外空间与建筑渲染',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'mecha-concept',
    name: 'Sci-Fi Mecha Concept',
    translatedName: '科幻机甲概念图',
    description: '硬核机械、重型装甲与未来战甲',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'chibi-3d',
    name: 'Cute Chibi Blindbox',
    translatedName: '萌系 Q 版盲盒玩具',
    description: '潮玩盲盒公仔与盲盒手办',
    provider: 'pollinations',
    category: '3d',
    isPopular: true,
  },
  {
    id: 'oil-painting',
    name: 'Classic Renaissance Oil Painting',
    translatedName: '文艺复兴古典油画',
    description: '大师级笔触与古典油画光感',
    provider: 'pollinations',
    category: 'realistic',
  },
  {
    id: 'ghibli-style',
    name: 'Studio Ghibli Anime',
    translatedName: '吉卜力风动漫',
    description: '温馨清新自然的日式童话画风',
    provider: 'pollinations',
    category: 'anime',
    isPopular: true,
  },
  {
    id: 'synthwave',
    name: '80s Synthwave Sunset',
    translatedName: '80年代 复古电子波',
    description: '复古日落、紫色调与复古网格',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'claymation',
    name: 'Cute Claymation Toy',
    translatedName: '可爱粘土定格动画',
    description: '手工泥塑与黏土风格',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'dark-fantasy',
    name: 'Dark Gothic Fantasy',
    translatedName: '暗黑哥特奇幻',
    description: '沉郁神话与哥特奇幻插画',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'pop-art',
    name: 'Pop Art Comics',
    translatedName: '美漫波普艺术',
    description: '美式漫画网点与鲜艳对比风格',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'paper-cut',
    name: 'Paper Cutout Origami Art',
    translatedName: '剪纸立体折纸艺术',
    description: '层叠剪纸与阴影折纸艺术',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'steampunk',
    name: 'Victorian Steampunk Machine',
    translatedName: '维多利亚蒸汽朋克',
    description: '铜质齿轮、蒸汽机械与复古英伦',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'flat-vector',
    name: 'Flat Vector Illustration',
    translatedName: '扁平矢量极简插画',
    description: '现代 UI 与网页设计矢量插画',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'low-poly',
    name: 'Low Poly Geometry World',
    translatedName: '低多边形几何世界',
    description: 'Low Poly 极简几何体造型',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'photorealism-portrait',
    name: 'Studio Master Portrait HD',
    translatedName: '大师人像摄影超清',
    description: '影棚专业人像打光与微距毛孔质感',
    provider: 'pollinations',
    category: 'realistic',
    isPopular: true,
  },
];
