import { ComputeEngine, AIModel, UserSettings } from '@/types';

export const DEFAULT_SETTINGS: UserSettings = {
  computeEngine: 'pollinations',
  defaultModel: 'black-forest-labs/FLUX.1-schnell',
  defaultSampler: 'Euler a',
  defaultAspectRatio: '1:1',
  defaultBatchCount: 1,
  defaultSteps: 25,
  defaultGuidance: 8.0,
  defaultStyleStrength: 0.65,
  defaultLoraWeight: 0.5,
  defaultNegativePrompt: 'blurry, low quality, distorted, extra limbs, bad hands, bad face, deformed, watermark',
  darkMode: false,
  historyLimit: 50,
  enableD1Sync: false,
  autoEnhancePrompt: true,
};

export const ASPECT_RATIOS = [
  { label: '1:1 正方形', value: '1:1', icon: '⏹️', w: 1024, h: 1024 },
  { label: '16:9 横屏', value: '16:9', icon: '🖥️', w: 1280, h: 720 },
  { label: '9:16 手机竖屏', value: '9:16', icon: '📱', w: 720, h: 1280 },
  { label: '4:3 经典小横屏', value: '4:3', icon: '🖼️', w: 1024, h: 768 },
  { label: '3:4 小竖屏', value: '3:4', icon: '📄', w: 768, h: 1024 },
];

export const SAMPLING_METHODS = [
  'Euler a',
  'DPM++ 2M Karras',
  'DPM++ SDE Karras',
  'DDIM',
  'LCM',
  'UniPC',
];

export const COMPUTE_ENGINES: ComputeEngine[] = [
  {
    id: 'siliconflow',
    name: 'SiliconFlow 硅基流动云算力',
    type: 'custom-api',
    endpoint: 'https://api.siliconflow.cn/v1/image/generations',
    description: '国内高速 AI 引擎，支持 Flux.1, SDXL, FLUX.1-schnell 高清全速生成',
    isDefault: false,
  },
  {
    id: 'openai',
    name: 'OpenAI DALL-E 3 官方引擎',
    type: 'dall-e',
    endpoint: 'https://api.openai.com/v1/images/generations',
    description: '顶级语言理解能力，生成细节严谨、逻辑逼真',
    isDefault: false,
  },
  {
    id: 'stability',
    name: 'Stability AI 官方节点',
    type: 'stable-diffusion',
    endpoint: 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image',
    description: 'SDXL 1.0 官方原汁原味生图引擎，色彩层次极高',
    isDefault: false,
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI (边缘计算)',
    type: 'cloudflare-ai',
    description: '基于 Cloudflare 全球边缘网络，低延迟无缝推理',
    isDefault: false,
  },
  {
    id: 'pollinations',
    name: 'Pollinations 免费开放算力池',
    type: 'pollinations',
    description: '免 API Key，全球节点联合算力，随时即用，零成本',
    isDefault: true,
  },
  {
    id: 'fal-ai',
    name: 'Fal.ai 高性能云端引擎',
    type: 'fal-ai',
    description: '极速 FLUX / SDXL 极速推演，秒级出图',
    isDefault: false,
  },
  {
    id: 'huggingface',
    name: 'HuggingFace Inference API',
    type: 'huggingface',
    description: '开源社区算力支持，兼容数千款 SD 模型',
    isDefault: false,
  },
];

export const AI_MODELS: AIModel[] = [
  {
    id: 'black-forest-labs/FLUX.1-schnell',
    name: 'FLUX.1 极速旗舰版 (推荐首选)',
    translatedName: 'FLUX.1 极速旗舰版',
    description: 'Black Forest Labs 最新代次画质王者，极致细节与质感',
    provider: 'pollinations',
    category: 'flux',
    isPopular: true,
    isFavorite: true,
    recommendedReason: '出图速度快、构图逼真、语义识别极高',
  },
  {
    id: 'black-forest-labs/FLUX.1-dev',
    name: 'FLUX.1 Dev 开发者专业版',
    translatedName: 'FLUX.1 开发者专业版',
    description: '具备 12B 参数量的超高精细度模型，写实感极佳',
    provider: 'pollinations',
    category: 'flux',
    isPopular: true,
  },
  {
    id: 'dall-e-3',
    name: 'OpenAI DALL·E 3 高清画质',
    translatedName: 'DALL·E 3 画质大模型',
    description: 'OpenAI 旗舰文生图大模型，复杂长句提示词精准还原',
    provider: 'openai',
    category: 'realistic',
    isPopular: true,
  },
  {
    id: 'stability-sdxl-1.0',
    name: 'SDXL 1.0 官方旗舰',
    translatedName: 'SDXL 1.0 官方大模型',
    description: 'Stability AI 经典 1024x1024 级高精画质大模型',
    provider: 'custom',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: '@cf/bytedance/stable-diffusion-xl-lightning',
    name: 'ByteDance SDXL Lightning (边缘极速)',
    translatedName: '字节跳动 Lightning 闪电大模型',
    description: '4-步极速推理，秒级呈现大作',
    provider: 'cloudflare',
    category: 'sdxl',
    cfModelPath: '@cf/bytedance/stable-diffusion-xl-lightning',
    isPopular: true,
  },
  {
    id: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    name: 'Cloudflare SDXL Base 1.0',
    translatedName: 'Cloudflare SDXL 原生大模型',
    description: '边缘高可用算力支持，画质稳定无暇',
    provider: 'cloudflare',
    category: 'sdxl',
    cfModelPath: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
  },
  {
    id: 'stabilityai/stable-diffusion-3.5-large',
    name: 'Stable Diffusion 3.5 Large',
    translatedName: 'SD 3.5 大型原生旗舰',
    description: '最新 SD 3.5 构图逻辑与光影质感',
    provider: 'pollinations',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: 'civitai:animagine-xl-3.1',
    name: 'Animagine XL 3.1 动漫大师版',
    translatedName: 'Animagine 二次元大师 3.1',
    description: '专业动漫与日系插画大模型，线条优雅细腻',
    provider: 'pollinations',
    category: 'anime',
    isPopular: true,
  },
  {
    id: 'civitai:anything-v5',
    name: 'Anything V5 精品二次元',
    translatedName: 'Anything V5 经典动漫',
    description: '经典通用型二次元绘图大模型，风格可塑性极高',
    provider: 'pollinations',
    category: 'anime',
  },
  {
    id: 'civitai:cyberrealistic-v4.1',
    name: 'CyberRealistic V4.1 赛博写实',
    translatedName: 'CyberRealistic 赛博现实主义',
    description: '专注极真实肖像、光彩肌理与摄影级质感',
    provider: 'pollinations',
    category: 'realistic',
    isPopular: true,
  },
  {
    id: 'civitai:dreamshaper-xl-v2',
    name: 'DreamShaper XL V2 梦幻塑造者',
    translatedName: 'DreamShaper 梦幻大模型 V2',
    description: '兼顾纪实写实与艺术创作的全能型引擎',
    provider: 'pollinations',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: 'civitai:vray-3d-render-xl',
    name: 'V-Ray 3D Render XL 超清渲染器',
    translatedName: 'V-Ray 3D 渲染大模型',
    description: '媲美电影级 3D CG 渲染效果',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'civitai:midjourney-v6-style',
    name: 'Midjourney V6 艺术唯美预设',
    translatedName: 'MJ V6 艺术唯美风',
    description: '模拟 Midjourney 极具震撼力的光影审美与艺术构图',
    provider: 'pollinations',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: 'civitai:rev-animated-v2',
    name: 'ReV Animated V2 奇幻动画',
    translatedName: 'ReV 奇幻 3D/2D 混合插画',
    description: '独具特色的 2.5D CG 插画质感',
    provider: 'pollinations',
    category: 'anime',
  },
  {
    id: 'civitai:meina-mix-v11',
    name: 'MeinaMix V11 魅奈二次元',
    translatedName: 'MeinaMix 极致动漫调教版',
    description: '唯美日漫水彩与光影氛围结合',
    provider: 'pollinations',
    category: 'anime',
  },
  {
    id: 'civitai:counterfeit-v3.0',
    name: 'Counterfeit V3.0 手绘插画版',
    translatedName: 'Counterfeit 手绘拟真动漫',
    description: '复古日系手绘与油画肌理效果',
    provider: 'pollinations',
    category: 'anime',
  },
  {
    id: 'civitai:deliberate-v3',
    name: 'Deliberate V3 深思纪实版',
    translatedName: 'Deliberate 精细纪实 V3',
    description: '丰富细节与自然构图的精细写实模型',
    provider: 'pollinations',
    category: 'realistic',
  },
  {
    id: 'civitai:realcartoon-xl-v6',
    name: 'RealCartoon XL V6 拟真欧美漫',
    translatedName: 'RealCartoon 3D 美漫写实',
    description: '迪士尼与皮克斯级别的 3D 动画质感',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'civitai:ink-wash-painting-xl',
    name: 'Ink Wash Painting 水墨国风',
    translatedName: '水墨写意传统国风大模型',
    description: '诗情画意的水墨与山水宣纸质感',
    provider: 'pollinations',
    category: 'sdxl',
    isPopular: true,
  },
  {
    id: 'civitai:ghibli-style-xl',
    name: 'Ghibli Style 吉卜力动画治愈风',
    translatedName: '吉卜力吉风治愈系',
    description: '充满阳光与清新色彩的吉卜力宫崎骏风格',
    provider: 'pollinations',
    category: 'anime',
  },
  {
    id: 'civitai:game-assets-3d-xl',
    name: 'Game Assets 3D 游戏资产建模',
    translatedName: '3D 游戏高精度资产模型',
    description: '适合生成游戏道具、场景原画与 3D 模型素材',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'civitai:cinematic-photography-v2',
    name: 'Cinematic Photography V2 电影剧照',
    translatedName: '电影胶片光影摄影版',
    description: '景深变焦、胶片颗粒与大师级构图氛围',
    provider: 'pollinations',
    category: 'realistic',
  },
  {
    id: 'civitai:cyberpunk-neon-city-xl',
    name: 'Cyberpunk Neon 赛博霓虹城市',
    translatedName: '赛博霓虹科幻大模型',
    description: '高对比霓虹发光与未来主义都市构图',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'civitai:watercolor-art-v3',
    name: 'Watercolor Art V3 灵动水彩画',
    translatedName: '灵动水彩纸张插画版',
    description: '晕染水彩与细腻纸张边缘质感',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'civitai:oil-painting-master-xl',
    name: 'Oil Painting Master 印象派油画',
    translatedName: '经典油画大师肌理版',
    description: '厚重笔触与古典油画光影色彩',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'civitai:pixel-art-master-v2',
    name: 'Pixel Art Master 像素复古风',
    translatedName: '像素艺术复古游戏版',
    description: '精美像素点阵与复古电子游戏氛围',
    provider: 'pollinations',
    category: 'sd15',
  },
  {
    id: 'civitai:chibi-sticker-cute',
    name: 'Chibi Cute Sticker Q版萌系贴纸',
    translatedName: 'Q版萌系表情贴纸版',
    description: '可爱线条与纯色干净背景贴纸',
    provider: 'pollinations',
    category: 'anime',
  },
  {
    id: 'civitai:isometric-3d-diorama',
    name: 'Isometric 3D Diorama 等距微缩模型',
    translatedName: '等距 3D 微缩景观模型',
    description: '精致立体等距切片与玩具模型视觉',
    provider: 'pollinations',
    category: '3d',
  },
  {
    id: 'civitai:dark-fantasy-gothic',
    name: 'Dark Fantasy Gothic 哥特暗黑范',
    translatedName: '哥特奇幻暗黑画质版',
    description: '神秘幽暗的光影与古典哥特美学',
    provider: 'pollinations',
    category: 'sdxl',
  },
  {
    id: 'civitai:low-poly-art-3d',
    name: 'Low Poly Art 3D 低多边形艺术',
    translatedName: 'Low Poly 低多边形 3D 艺术',
    description: '现代几何切面与清爽明亮色彩',
    provider: 'pollinations',
    category: '3d',
  },
];

export const PRESET_MODELS = AI_MODELS;
